FROM node:21-alpine3.18

# Set the working directory
WORKDIR /app

# Copy package.json and tsconfig.json first
COPY package.json .
COPY tsconfig.json .

# Install dependencies using Yarn
RUN yarn install --frozen-lockfile --production

# Copy the source code
COPY src ./src
COPY public ./public

# Install nodemon globally (if needed)
RUN yarn global add nodemon

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["yarn", "run", "start:dev"]
