name: Deploy simple_project EC2

on:
  push:
    branches:
      - main
    paths:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2" # Change to your AWS region
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Create a tarball of the project
          tar -czf simple_project.tar.gz ./*

          # Copy the tarball to the EC2 instance
          scp -i $EC2_SSH_KEY -o StrictHostKeyChecking=no simple_project.tar.gz ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

          # Connect to the EC2 instance and deploy the project
          ssh -i $EC2_SSH_KEY -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Extract the project tarball
            tar -xzf /home/ec2-user/simple_project.tar.gz -C /home/ec2-user/simple_project

            # Change to the project directory
            cd /home/ec2-user/simple_project

            # Install dependencies and start the project
            npm install
            npm start
          EOF
