name: Deploy  to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy setup_envaironment.sh to EC2
        run: scp -o StrictHostKeyChecking=no -i simple_project.pem setup_envaironment.sh ubuntu@ec2-18-207-196-252.compute-1.amazonaws.com:~

      - name: Run setup_envaironment.sh on EC2
        run: ssh -o StrictHostKeyChecking=no -i simple_project.pem ubuntu@ec2-18-207-196-252.compute-1.amazonaws.com 'chmod +x ~/setup_envaironment.sh && ~/setup_envaironment.sh'
